# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dust_detective.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loadImg_ = QtWidgets.QPushButton(self.centralwidget)
        self.loadImg_.setObjectName("loadImg_")
        self.horizontalLayout.addWidget(self.loadImg_)
        self.saveImg_ = QtWidgets.QPushButton(self.centralwidget)
        self.saveImg_.setObjectName("saveImg_")
        self.horizontalLayout.addWidget(self.saveImg_)
        self.clear_ = QtWidgets.QPushButton(self.centralwidget)
        self.clear_.setObjectName("clear_")
        self.horizontalLayout.addWidget(self.clear_)
        self.addLabel_ = QtWidgets.QCheckBox(self.centralwidget)
        self.addLabel_.setChecked(True)
        self.addLabel_.setObjectName("addLabel_")
        self.horizontalLayout.addWidget(self.addLabel_)
        self.rank5_acc = QtWidgets.QCheckBox(self.centralwidget)
        self.rank5_acc.setChecked(True)
        self.rank5_acc.setObjectName("rank5_acc")
        self.horizontalLayout.addWidget(self.rank5_acc)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.image_ = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.image_.setFont(font)
        self.image_.setText("")
        self.image_.setScaledContents(True)
        self.image_.setObjectName("image_")
        self.verticalLayout_3.addWidget(self.image_)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.previous_ = QtWidgets.QPushButton(self.centralwidget)
        self.previous_.setObjectName("previous_")
        self.horizontalLayout_3.addWidget(self.previous_)
        self.next_ = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.next_.setFont(font)
        self.next_.setObjectName("next_")
        self.horizontalLayout_3.addWidget(self.next_)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.setStretch(0, 9)
        self.verticalLayout_3.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.result_ = QtWidgets.QTextBrowser(self.centralwidget)
        self.result_.setAutoFormatting(QtWidgets.QTextEdit.AutoAll)
        self.result_.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.result_.setLineWrapColumnOrWidth(2)
        self.result_.setObjectName("result_")
        self.verticalLayout_2.addWidget(self.result_)
        self.verticalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_6.addWidget(self.line_3)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.image_next_ = QtWidgets.QLabel(self.centralwidget)
        self.image_next_.setText("")
        self.image_next_.setObjectName("image_next_")
        self.verticalLayout_6.addWidget(self.image_next_)
        self.verticalLayout_6.setStretch(0, 4)
        self.verticalLayout_6.setStretch(3, 4)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 6)
        self.gridLayout.setColumnStretch(1, 3)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(2, 9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DustDetective"))
        self.loadImg_.setText(_translate("MainWindow", "Load Image(s)"))
        self.saveImg_.setText(_translate("MainWindow", "Save Image(s)"))
        self.clear_.setText(_translate("MainWindow", "Clear"))
        self.addLabel_.setText(_translate("MainWindow", "Add Label Mark"))
        self.rank5_acc.setText(_translate("MainWindow", "Add Rank-5 Acc"))
        self.previous_.setText(_translate("MainWindow", "<= Previous"))
        self.next_.setText(_translate("MainWindow", "Next =>"))
        self.label_2.setText(_translate("MainWindow", "Result:"))
        self.label_3.setText(_translate("MainWindow", "Next:"))

